### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by mrprovoker** [IvanCen/yandex__git_validation#1]
Добрый день.

В целом хорошо, но есть некоторые вопросы.

**Надо исправить:**
- Из-за атрибута **novalidate** cейчас можно отправить пустые поля. Форма должна отправляться только в случае успешной валидации всех полей.
- Сейчас все инпуты имеют одинаковый атрибут name="name", хотя такой name подходит только полю: "Имя"
- В репозитории есть временный файл, не относящийся к проекту - .DS_Store. Таких файлов в репозитории не должно быть. Для это обычно в проект помещается файл .gitignore, где перечисляют файлы и папки, которые не должны попадать в проект
- Проект должен быть доступен на github.io, а в README должна быть ссылка на этот проект
- Проблемы валидации полей:
1 Проходят валидацию следующие невалидные имена:
- `Авы312`
- `12`
- `Ав--`
- `--`
- `Ана-Anna`
- `Анна-Мария-Анна`

2. Не проходит валидацию такой валидный почтовый ящик:
- `my.ownsite@ourearth.org`

3. Проходит валидацию такой невалидный почтовый ящик:
- `mysite123@gmail.b` (tld не может быть однобуквенным)

4. Проходят валидацию следующие невалидные телефонные номера:
- `+7 (123) 456---------78-90`
- `+70`
- `+9---`

5. Проходят валидацию такие невалидные IP-адреса/домены:
- `http://mysite..ru`
- `http://255.255` - tld не может быть из цифр
- `http://255.255.255.0333` - в каждой группе цифр может быть число о 0 до 255
- `http://255.255.255.-1`
- `http://255.255.255.1:8` - минимальный порт по заданию должен состоять из двух чисел

Можно лучше:
- Есть пустой файл `script.js`. Лишних файлов в проектах не должно быть

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

**Comment by IvanCen** [comment]
Все исправил.
Но есть проблема паттерна валидации URL, сервисы проверки regexp проходит такая регулярка, но при использовании внутри браузера вылетает ошибка в консоль: `Invalid escape`.  С чем она связана? Саму регулярку менял по всякому и спрашивал у знающих людей, они в первый раз с таким сталкиваются.

**Comment by mrprovoker** [comment]
Спасибо за правки стало значительно лучше и большинство правок исправлено. Есть еще небольшие неточности в проверках.

**Надо исправить:**
- Не проходит валидацию двухбуквенное имя, например `Ян`.
- Проходит валидацию такой невалидный почтовый ящик: `mysite..1234@yahoo.com` (не может быть двух точек вподряд)
- Проходит валдицию такой телефонный номер: `+7 (123 456-78-90`

Для понимания - по заданию достаточно поддержать только 6 возможных форматов, которые были в примерах задания:
```
+7 (123) 456-78-90
+7(925)900-90-90
+7(925) 900-90-90
+7 925-900-90-90
+79259009090
89259009090
```
И достаточно будет, чтобы любое отклонение от этих форматов - не проходило валидацию.


- Проходит валидацию такие невалидные урлы: 
```
https://my
https://my.я
https://.ru
http://255.255
http://255.255 .      255.1:8
```

- Присутствует ошибка валидации url'a в консоле. К сожалению с ней не смогу принять работу. Мне WebStorm коричневым подчеркнул в регулярке лишние escape-символы. Возможно дело в них. Прикладываю картинку. Если не получится разобраться - можно будет попросить помощи у наставника.


Рекомендую после правок основательно самостоятельно потестировать формы на соответствие заданию разными кейсами.


Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

![image](https://user-images.githubusercontent.com/10175487/74306602-d30ba900-4d84-11ea-9500-8f0093840e3e.png)

**Comment by IvanCen** [comment]
Спасибо! Благодаря вам и вашему WebStorm, решил проблему.   
Редакторы регулярок и VSсode не видели лишние escape-символы.
Все исправил, прогнал по многим кейсам каждую регулярку на соответствие.
Теперь все должно работать как надо.

**Comment by mrprovoker** [comment]
Рад слышать, что проблема с ошибкой решилась. 

Отлчино, что  сейчас полностью корректны проверки имени, телефона и сайта.

У поле email есть одно небольшое несоответствие с заданием.

**Надо исправить:**
- Проходит валидацию email с кириллицей в tld, например `mysite@rsia.ыуъv`. По заданию - `только латиница`.


Жду эту небольшую доработку и после этого смогу принять задание.

**Comment by mrprovoker** [comment]
Отличная работа, все пункты задания выполнены в полном объеме. Задание принято 👍

Желаю успехов в дальнейшем обучении!
